function getSites() {
  const jQuery = function() {};
  let number = 0;

  const sites = [];

  function add(arg1, arg2, name, url, arg3, lat, lng, html) {
    sites.push({name: name, url: url, lat: lat, lng: lng});
  }

  // -- The following is copy-pasted from http://hotpoticeland.com/category/hotpots/ --

  add(jQuery(this), number += 1, "Fosslaug", "http://hotpoticeland.com/fosslaug/","","65.495732","-19.382117", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/fosslaug_992-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="fosslaug_992" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Hoffell');
  add(jQuery(this), number += 1, "Hoffell", "http://hotpoticeland.com/hoffell/","","64.397096","-15.340819", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/hofell-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="hofell" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Guðrúnarlaug');
  add(jQuery(this), number += 1, "Guðrúnarlaug", "http://hotpoticeland.com/gudrunarlaug/","","65.247320","-21.807181", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/gudrunarlaug.-2-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="gudrunarlaug.-2" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Austurengjahver');
  add(jQuery(this), number += 1, "Austurengjahver", "http://hotpoticeland.com/austurengjahver/","","63.889215","-22.032132", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Austurengjahver-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Austurengjahver" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Hellulaug');
  add(jQuery(this), number += 1, "Hellulaug", "http://hotpoticeland.com/hellulaug-2/","","65.572580","-23.172544", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Hellulaug31.8.2012-14-42-07-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Hellulaug(31.8.2012 14-42-07)" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Secret lagoon');
  add(jQuery(this), number += 1, "Secret lagoon", "http://hotpoticeland.com/secret-lagoon/","","64.137429","-20.309325", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/secret-lagoon-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="secret lagoon" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Haukadalslaug');
  add(jQuery(this), number += 1, "Haukadalslaug", "http://hotpoticeland.com/haukadalslaug/","","64.310333","-20.301467", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/haukadalur-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="haukadalur" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Sturlungalaug (Guðmunarlaug)');
  add(jQuery(this), number += 1, "Sturlungalaug (Guðmunarlaug)", "http://hotpoticeland.com/sturlungalaug-gudmunarlaug/","","64.869617"," -22.283783", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/sturlunglaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="sturlunglaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Snorralaug');
  add(jQuery(this), number += 1, "Snorralaug", "http://hotpoticeland.com/snorralaug/","","64.663985","-21.291202", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Snorralaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Snorralaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Pollurinn');
  add(jQuery(this), number += 1, "Pollurinn", "http://hotpoticeland.com/pollurinn/","","65.660043","-23.914704", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/pollurin-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="pollurin" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Laugaland');
  add(jQuery(this), number += 1, "Laugaland", "http://hotpoticeland.com/laugaland/","","65.512087","-22.303976", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/image-not-available_13-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="image-not-available_13" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Kvika (footbath)');
  add(jQuery(this), number += 1, "Kvika (footbath)", "http://hotpoticeland.com/kvika-footbath/","","64.162216","-22.007428", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Kvika-footbath-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Kvika-footbath" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Kaldbakslaug');
  add(jQuery(this), number += 1, "Kaldbakslaug", "http://hotpoticeland.com/kaldbakslaug/","","66.015884","-17.358850", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Kaldbakslaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Kaldbakslaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Hveragil');
  add(jQuery(this), number += 1, "Hveragil", "http://hotpoticeland.com/hveragil/","","64.676647","-16.504898", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/hveragil-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="hveragil" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Hörgshlíð');
  add(jQuery(this), number += 1, "Hörgshlíð", "http://hotpoticeland.com/horgshlid/","","65.845221","-22.611451", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/image-not-available_13-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="image-not-available_13" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Gjörvidalslaug');
  add(jQuery(this), number += 1, "Gjörvidalslaug", "http://hotpoticeland.com/gjorvidalslaug/","","65.826512","-22.446699", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Gjörvidalslaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Gjörvidalslaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Laugarvallalaug‏‎');
  add(jQuery(this), number += 1, "Laugarvallalaug‏‎", "http://hotpoticeland.com/laugarvallalaug%e2%80%8f%e2%80%8e/","","65.006500","-15.762233", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/image-not-available_13-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="image-not-available_13" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Siká');
  add(jQuery(this), number += 1, "Siká", "http://hotpoticeland.com/sika/","","64.998433","-20.931700", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/image-not-available_13-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="image-not-available_13" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Borhola Kerlingafjöllum');
  add(jQuery(this), number += 1, "Borhola Kerlingafjöllum", "http://hotpoticeland.com/borhola-kerlingafjollum/","","64.654074","-19.273599", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Kerlingafjölllaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Kerlingafjölllaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Brimketill');
  add(jQuery(this), number += 1, "Brimketill", "http://hotpoticeland.com/brimketill/","","63.819106","-22.603357", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Brimketill-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Brimketill" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Brúarpotturinn');
  add(jQuery(this), number += 1, "Brúarpotturinn", "http://hotpoticeland.com/bruarpotturinn/","","65.656762","-23.911271", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Brúarpotturinn-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Brúarpotturinn" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Djúpavogskörin');
  add(jQuery(this), number += 1, "Djúpavogskörin", "http://hotpoticeland.com/djupavogskorin/","","64.654387","-14.337690", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Djúpavogskorin-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Djúpavogskorin" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Englandshverir');
  add(jQuery(this), number += 1, "Englandshverir", "http://hotpoticeland.com/englandshverir/","","64.490598","-21.178508", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Englandshverir-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Englandshverir" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Galtahryggjarlaug');
  add(jQuery(this), number += 1, "Galtahryggjarlaug", "http://hotpoticeland.com/galtahryggjarlaug/","","65.848400","-22.652049", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Galtahryggjarlaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Galtahryggjarlaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Guðlaug');
  add(jQuery(this), number += 1, "Guðlaug", "http://hotpoticeland.com/gudlaug/","","64.121843","-17.546711", '','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Gvendarlaug');
  add(jQuery(this), number += 1, "Gvendarlaug", "http://hotpoticeland.com/gvendarlaug/","","65.781660","-21.568222", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/gvendarlaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="gvendarlaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Hákarlavogur');
  add(jQuery(this), number += 1, "Hákarlavogur", "http://hotpoticeland.com/hakarlavogur/","","65.998509","-21.317182", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Hákarlavogur-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Hákarlavogur" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Hólsgerðislaug');
  add(jQuery(this), number += 1, "Hólsgerðislaug", "http://hotpoticeland.com/holsgerdislaug/","","65.302808","-18.255904", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Hólsgerðislaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Hólsgerðislaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Hrunalaug');
  add(jQuery(this), number += 1, "Hrunalaug", "http://hotpoticeland.com/hrunalaug/","","64.139590","-20.260480", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/hrunalaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="hrunalaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Hvalfjarðarlaug');
  add(jQuery(this), number += 1, "Hvalfjarðarlaug", "http://hotpoticeland.com/hvalfjardarlaug/","","64.373669","-21.563894", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Hvalfjarðarlaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Hvalfjarðarlaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Hveravallalaug');
  add(jQuery(this), number += 1, "Hveravallalaug", "http://hotpoticeland.com/hveravallalaug/","","64.866305","-19.554033", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Hveravallalaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Hveravallalaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Klambragilslaug');
  add(jQuery(this), number += 1, "Klambragilslaug", "http://hotpoticeland.com/klambragilslaug/","","64.025701","-21.212476", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Klambragil-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Klambragil" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Krosslaug (Reykjalaug)');
  add(jQuery(this), number += 1, "Krosslaug (Reykjalaug)", "http://hotpoticeland.com/krosslaug-reykjalaug/","","64.494562","-21.175571", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Krosslaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Krosslaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Kúalaug');
  add(jQuery(this), number += 1, "Kúalaug", "http://hotpoticeland.com/kualaug/","","64.328714","-20.271917", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Kúalaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Kúalaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Laugarvallardalur');
  add(jQuery(this), number += 1, "Laugarvallardalur", "http://hotpoticeland.com/laugarvallardalur-hot-pot/","","65.029640","-15.958474", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/LAUGARVALLARDALUR-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="LAUGARVALLARDALUR" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Stjáni');
  add(jQuery(this), number += 1, "Stjáni", "http://hotpoticeland.com/stjani/","","64.841637","-23.217873", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/stjani-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="stjani" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Lýsuhólslaug');
  add(jQuery(this), number += 1, "Lýsuhólslaug", "http://hotpoticeland.com/lysuholslaug/","","64.846001","-23.337450", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Lýsuhólslaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Lýsuhólslaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Strútslaug');
  add(jQuery(this), number += 1, "Strútslaug", "http://hotpoticeland.com/strutslaug/","","63.867900","-18.948026", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Strútslaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Strútslaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Vígðalaug');
  add(jQuery(this), number += 1, "Vígðalaug", "http://hotpoticeland.com/vigdalaug/","","64.215727","-20.731476", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Vígðalaug1-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Vígðalaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Víti');
  add(jQuery(this), number += 1, "Víti", "http://hotpoticeland.com/viti/","","65.047027","-16.726766", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/viti-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="viti" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Þórunnarlaug');
  add(jQuery(this), number += 1, "Þórunnarlaug", "http://hotpoticeland.com/porunnarlaug/","","65.027805","-18.332427", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Pórunnarlaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Pórunnarlaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Gunnuhver');
  add(jQuery(this), number += 1, "Gunnuhver", "http://hotpoticeland.com/gunnuhver/","","63.846054","-22.444725", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/gunnuhver-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="gunnuhver" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Skátalaug');
  add(jQuery(this), number += 1, "Skátalaug", "http://hotpoticeland.com/skatalaug/","","63.903933","-22.043317", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/skátalaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="skátalaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Krýsuvík');
  add(jQuery(this), number += 1, "Krýsuvík", "http://hotpoticeland.com/krysuvik/","","63.894010","-22.051215", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/krysuvik-2-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="krysuvik 2" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Rjúpnabrekkur');
  add(jQuery(this), number += 1, "Rjúpnabrekkur", "http://hotpoticeland.com/rjupnabrekkur/","","64.016690"," -21.232117", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/rjupnabrekkur-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="rjupnabrekkur" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Geysir');
  add(jQuery(this), number += 1, "Geysir", "http://hotpoticeland.com/geysir/","","64.313959","-20.301388", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Geysir-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Geysir" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Marteinslaug');
  add(jQuery(this), number += 1, "Marteinslaug", "http://hotpoticeland.com/marteinslaug/","","64.326750","-20.282000", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Marteinslaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Marteinslaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Hveravellir');
  add(jQuery(this), number += 1, "Hveravellir", "http://hotpoticeland.com/hveravellir/","","64.866083","-19.553033", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Hveravellir-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Hveravellir" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Landbrotalaug');
  add(jQuery(this), number += 1, "Landbrotalaug", "http://hotpoticeland.com/landbrotalaug/","","64.832217","-22.318500", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/landbrotalaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="landbrotalaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Grafarlaug');
  add(jQuery(this), number += 1, "Grafarlaug", "http://hotpoticeland.com/grafarlaug/","","64.960867","-21.516433", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/grafarlaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="grafarlaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Hveraborg');
  add(jQuery(this), number += 1, "Hveraborg", "http://hotpoticeland.com/hveraborg/","","65.094983","-21.019249", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Hveraborg-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Hveraborg" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Grjótagjá');
  add(jQuery(this), number += 1, "Grjótagjá", "http://hotpoticeland.com/grjotagja/","","65.626433","-16.882483", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Grjotagja-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Grjotagja" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Námafjall');
  add(jQuery(this), number += 1, "Námafjall", "http://hotpoticeland.com/namafjall/","","65.642459","-16.808649", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/namafjall-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="namafjall" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Laugarfell');
  add(jQuery(this), number += 1, "Laugarfell", "http://hotpoticeland.com/laugarfell/","","64.885861","-15.351343", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/laugarfell-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="laugarfell" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Stóragjá');
  add(jQuery(this), number += 1, "Stóragjá", "http://hotpoticeland.com/storagja/","","65.638554","-16.910588", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Stóragjá2-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Stóragjá" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Hólsgerði');
  add(jQuery(this), number += 1, "Hólsgerði", "http://hotpoticeland.com/holsgerdi/","","65.307386","-18.255295", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Hólsgerði-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Hólsgerði" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Ostakarið');
  add(jQuery(this), number += 1, "Ostakarið", "http://hotpoticeland.com/ostakarid/","","66.055341","-17.351982", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Ostakarið-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Ostakarið" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Biskupslaug');
  add(jQuery(this), number += 1, "Biskupslaug", "http://hotpoticeland.com/biskupslaug/","","65.660372","-19.083308", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/biskupslaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="biskupslaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Grettislaug');
  add(jQuery(this), number += 1, "Grettislaug", "http://hotpoticeland.com/grettislaug/","","65.881421","-19.736811", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Grettislaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Grettislaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Hot tubs at Drangsnes');
  add(jQuery(this), number += 1, "Hot tubs at Drangsnes", "http://hotpoticeland.com/hot-tubs-at-drangsnes/","","65.688751","-21.453911", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Hot-tubs-at-Drangsnes-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Hot tubs at Drangsnes" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Reykjafjarðarlaug');
  add(jQuery(this), number += 1, "Reykjafjarðarlaug", "http://hotpoticeland.com/reykjafjardarlaug/","","65.623070","-23.468884", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Reykjafjarðarlaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Reykjafjarðarlaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Hellulaug');
  add(jQuery(this), number += 1, "Hellulaug", "http://hotpoticeland.com/hellulaug/","","65.587964","-23.141477", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Hellulaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Hellulaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Hörgshlíðarlaug');
  add(jQuery(this), number += 1, "Hörgshlíðarlaug", "http://hotpoticeland.com/horgshlidarlaug/","","65.830689","-22.629719", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/horgshlídarlaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="horgshlídarlaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Seljavellir');
  add(jQuery(this), number += 1, "Seljavellir", "http://hotpoticeland.com/seljavellir/","","63.565885","-19.608744", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/seljavellir-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="seljavellir" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Landmannalaugar');
  add(jQuery(this), number += 1, "Landmannalaugar", "http://hotpoticeland.com/landmannalaugar/","","63.987048","-19.061365", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Landmannalaugar1-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Landmannalaugar" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Laugafell');
  add(jQuery(this), number += 1, "Laugafell", "http://hotpoticeland.com/laugafell/","","65.026979","-18.329830", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/laugafell-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="laugafell" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');                  	console.log('Nauteyrarlaug');
  add(jQuery(this), number += 1, "Nauteyrarlaug", "http://hotpoticeland.com/nauteyrarlaug-2/","","65.934505","-22.376232", '<img width="95" height="95" src="http://hotpoticeland.com/wp-content/uploads/Nauteyrarlaug-95x95.jpg" class="attachment-post-thumbnail wp-post-image" alt="Nauteyrarlaug" />','http://hotpoticeland.com/wp-content/themes/wpnavigator/images/pin_6.png');

  // -- END COPY PASTE --

  return sites;
}

const sites = getSites();

sites.forEach(site => site.pathName = decodeURIComponent(site.url.match('/([^/]+)/$')[1]));

module.exports = sites;
